/**
 * Every source the course cites, in APA style (7th edition), with the lessons
 * that use it. *Asterisks* mark italics (titles of books, reports and pages;
 * journal names and volumes). Sorted by the tests, so add entries anywhere.
 *
 * Journal-article details (authors, year, title, journal, volume, issue, pages)
 * were checked against Crossref for every DOI on 2026-10-05; preprints against
 * arXiv. Made-up sources planted in exercises are not listed: they don't exist.
 *
 * This list supports the claims in claims.js; it does not replace them. A
 * source here is not an attestation.
 */

export const SOURCES = [
  { lessons: [3], apa: "Adolescent Sleep Working Group, Committee on Adolescence, & Council on School Health. (2014). School start times for adolescents. *Pediatrics, 134*(3), 642–649.", url: "https://doi.org/10.1542/peds.2014-1697" },
  { lessons: [9], apa: "American Psychiatric Association. (2022). *Diagnostic and statistical manual of mental disorders* (5th ed., text rev.).", url: "https://doi.org/10.1176/appi.books.9780890425787" },
  { lessons: [10], apa: "Back, M. D., Schmukle, S. C., & Egloff, B. (2010). Why are narcissists so charming at first sight? Decoding the narcissism–popularity link at zero acquaintance. *Journal of Personality and Social Psychology, 98*(1), 132–145.", url: "https://doi.org/10.1037/a0016338" },
  { lessons: [3], apa: "Black, P., & Wiliam, D. (1998). Inside the black box: Raising standards through classroom assessment. *Phi Delta Kappan, 80*(2), 139–148." },
  { lessons: [3], apa: "Bloom, B. S. (1984). The 2 sigma problem: The search for methods of group instruction as effective as one-to-one tutoring. *Educational Researcher, 13*(6), 4–16.", url: "https://doi.org/10.3102/0013189X013006004" },
  { lessons: [7], apa: "Brignull, H. (2010). *Deceptive patterns* [Website, first published as Dark Patterns].", url: "https://www.deceptive.design/" },
  { lessons: [10], apa: "Buckels, E. E., Jones, D. N., & Paulhus, D. L. (2013). Behavioral confirmation of everyday sadism. *Psychological Science, 24*(11), 2201–2209.", url: "https://doi.org/10.1177/0956797613490749" },
  { lessons: [10], apa: "Buckels, E. E., Trapnell, P. D., & Paulhus, D. L. (2014). Trolls just want to have fun. *Personality and Individual Differences, 67*, 97–102.", url: "https://doi.org/10.1016/j.paid.2014.01.016" },
  { lessons: [6], apa: "Center for Universal Design. (1997). *The principles of universal design* (Version 2.0). North Carolina State University." },
  { lessons: [12], apa: "Child Helpline International. (n.d.). *Child helplines*. Retrieved October 5, 2026, from", url: "https://childhelplineinternational.org/helplines/" },
  { lessons: [12], apa: "Child Welfare Information Gateway. (n.d.). *Mandatory reporting of child abuse and neglect*. U.S. Department of Health and Human Services, Children's Bureau.", url: "https://cwig-prod-prod-drupal-s3fs-us-east-1.s3.amazonaws.com/public/documents/manda.pdf" },
  { lessons: [5], apa: "College Board. (n.d.). *SAT Suite of Assessments*.", url: "https://satsuite.collegeboard.org/" },
  { lessons: [8], apa: "Committee on the Rights of the Child. (2021). *General comment No. 25 (2021) on children's rights in relation to the digital environment* (CRC/C/GC/25). United Nations.", url: "https://www.ohchr.org/en/documents/general-comments-and-recommendations/general-comment-no-25-2021-childrens-rights-relation" },
  { lessons: [5], apa: "Court of Justice of the European Union. (2020). *Data Protection Commissioner v. Facebook Ireland Ltd and Maximillian Schrems* (Case C-311/18). ECLI:EU:C:2020:559." },
  { lessons: [11], apa: "De Freitas, J., Oğuz-Uğuralp, Z., & Uğuralp, A. K. (2025). *Emotional manipulation by AI companions* (Harvard Business School Working Paper No. 26-005). arXiv.", url: "https://doi.org/10.48550/arXiv.2508.19258" },
  { lessons: [12], apa: "Department for Education. (2026). *Keeping children safe in education 2026: Statutory guidance for schools and colleges*. GOV.UK.", url: "https://www.gov.uk/government/publications/keeping-children-safe-in-education--2" },
  { lessons: [10], apa: "Douglas, J. E., & Munn, C. (1992). Violent crime scene analysis: Modus operandi, signature, and staging. *FBI Law Enforcement Bulletin, 61*(2), 1–10." },
  { lessons: [1], apa: "Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J., & Willingham, D. T. (2013). Improving students' learning with effective learning techniques: Promising directions from cognitive and educational psychology. *Psychological Science in the Public Interest, 14*(1), 4–58.", url: "https://doi.org/10.1177/1529100612453266" },
  { lessons: [1], apa: "Ebbinghaus, H. (1885). *Über das Gedächtnis: Untersuchungen zur experimentellen Psychologie* [On memory: Investigations in experimental psychology]. Duncker & Humblot." },
  { lessons: [10], apa: "eSafety Commissioner. (n.d.). *Unsafe contact and \"grooming\"*. Australian Government.", url: "https://www.esafety.gov.au/young-people/unsafe-contact" },
  { lessons: [5], apa: "European Commission. (2023). *Commission implementing decision on the adequate level of protection of personal data under the EU–US Data Privacy Framework* (C(2023) 4745)." },
  { lessons: [1, 5], apa: "European Parliament & Council of the European Union. (2016). Regulation (EU) 2016/679 (General Data Protection Regulation). *Official Journal of the European Union, L 119*, 1–88.", url: "https://eur-lex.europa.eu/eli/reg/2016/679/oj" },
  { lessons: [7], apa: "European Parliament & Council of the European Union. (2022). Regulation (EU) 2022/2065 (Digital Services Act). *Official Journal of the European Union, L 277*, 1–102.", url: "https://eur-lex.europa.eu/eli/reg/2022/2065/oj" },
  { lessons: [10], apa: "Federal Bureau of Investigation. (n.d.). *Behavioral analysis*.", url: "https://www.fbi.gov/how-we-investigate/behavioral-analysis" },
  { lessons: [12], apa: "Federal Bureau of Investigation. (n.d.). *Sextortion*.", url: "https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/sextortion" },
  { lessons: [7], apa: "Federal Trade Commission. (2022). *Bringing dark patterns to light* [Staff report].", url: "https://www.ftc.gov/reports/bringing-dark-patterns-light" },
  { lessons: [3], apa: "Federal Trade Commission. (n.d.). *CAN-SPAM Act: A compliance guide for business*.", url: "https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business" },
  { lessons: [10], apa: "Fowler, K. A., Lilienfeld, S. O., & Patrick, C. J. (2009). Detecting psychopathy from thin slices of behavior. *Psychological Assessment, 21*(1), 68–78.", url: "https://doi.org/10.1037/a0014938" },
  { lessons: [6], apa: "Friedman, B. (1996). Value-sensitive design. *Interactions, 3*(6), 16–23.", url: "https://doi.org/10.1145/242485.242493" },
  { lessons: [10], apa: "Goodboy, A. K., & Martin, M. M. (2015). The personality profile of a cyberbully: Examining the Dark Triad. *Computers in Human Behavior, 49*, 1–4.", url: "https://doi.org/10.1016/j.chb.2015.02.052" },
  { lessons: [8], apa: "Grossmann, I., Weststrate, N. M., Ardelt, M., Brienza, J. P., Dong, M., Ferrari, M., Fournier, M. A., Hu, C. S., Nusbaum, H. C., & Vervaeke, J. (2020). The science of wisdom in a polarized world: Knowns and unknowns. *Psychological Inquiry, 31*(2), 103–133.", url: "https://doi.org/10.1080/1047840X.2020.1750917" },
  { lessons: [8], apa: "Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social relationships and mortality risk: A meta-analytic review. *PLoS Medicine, 7*(7), Article e1000316.", url: "https://doi.org/10.1371/journal.pmed.1000316" },
  { lessons: [10], apa: "Home Office. (2023). *Controlling or coercive behaviour statutory guidance framework*. GOV.UK.", url: "https://assets.publishing.service.gov.uk/media/642d3f9e7de82b001231364d/Controlling_or_Coercive_Behaviour_Statutory_Guidance_-_final.pdf" },
  { lessons: [5], apa: "International Astronomical Union. (2006). *Resolution B5: Definition of a planet in the Solar System*." },
  { lessons: [6], apa: "International Organization for Standardization. (2018). *Ergonomics of human-system interaction — Part 11: Usability: Definitions and concepts* (ISO Standard No. 9241-11:2018)." },
  { lessons: [6], apa: "International Organization for Standardization. (2019). *Ergonomics of human-system interaction — Part 210: Human-centred design for interactive systems* (ISO Standard No. 9241-210:2019)." },
  { lessons: [9], apa: "Jauk, E., & Dieterich, R. (2019). Addiction and the Dark Triad of personality. *Frontiers in Psychiatry, 10*, Article 662.", url: "https://doi.org/10.3389/fpsyt.2019.00662" },
  { lessons: [9], apa: "Jonason, P. K., Slomski, S., & Partyka, J. (2012). The Dark Triad at work: How toxic employees get their way. *Personality and Individual Differences, 52*(3), 449–453.", url: "https://doi.org/10.1016/j.paid.2011.11.008" },
  { lessons: [9], apa: "Jonason, P. K., & Webster, G. D. (2012). A protean approach to social influence: Dark Triad personalities and social influence tactics. *Personality and Individual Differences, 52*(4), 521–526.", url: "https://doi.org/10.1016/j.paid.2011.11.023" },
  { lessons: [9], apa: "Jones, D. N., & Paulhus, D. L. (2014). Introducing the Short Dark Triad (SD3): A brief measure of dark personality traits. *Assessment, 21*(1), 28–41.", url: "https://doi.org/10.1177/1073191113514105" },
  { lessons: [1, 11], apa: "Jurafsky, D., & Martin, J. H. (2026). *Speech and language processing* (3rd ed. draft).", url: "https://web.stanford.edu/~jurafsky/slp3/" },
  { lessons: [1, 3], apa: "Kandpal, N., Deng, H., Roberts, A., Wallace, E., & Raffel, C. (2023). Large language models struggle to learn long-tail knowledge. In *Proceedings of the 40th International Conference on Machine Learning* (Vol. 202, pp. 15696–15707). PMLR.", url: "https://proceedings.mlr.press/v202/kandpal23a.html" },
  { lessons: [11], apa: "Kran, E., Nguyen, H. M., Kundu, A., Jawhar, S., Park, J., & Jurewicz, M. M. (2025). DarkBench: Benchmarking dark patterns in large language models. In *Proceedings of the Thirteenth International Conference on Learning Representations (ICLR 2025)*.", url: "https://doi.org/10.48550/arXiv.2503.10728" },
  { lessons: [1], apa: "Lewis, P., Perez, E., Piktus, A., Petroni, F., Karpukhin, V., Goyal, N., Küttler, H., Lewis, M., Yih, W., Rocktäschel, T., Riedel, S., & Kiela, D. (2020). Retrieval-augmented generation for knowledge-intensive NLP tasks. In *Advances in Neural Information Processing Systems 33* (NeurIPS 2020).", url: "https://doi.org/10.48550/arXiv.2005.11401" },
  { lessons: [3], apa: "*Mata v. Avianca, Inc.*, 678 F. Supp. 3d 443 (S.D.N.Y. 2023)." },
  { lessons: [1], apa: "NASA. (n.d.). *Apollo 11*.", url: "https://www.nasa.gov/mission/apollo-11/" },
  { lessons: [12], apa: "National Center for Missing & Exploited Children. (n.d.). *Take It Down*.", url: "https://takeitdown.ncmec.org/" },
  { lessons: [6], apa: "Nielsen, J. (1993). *Usability engineering*. Academic Press." },
  { lessons: [6], apa: "Nielsen, J. (1994). *10 usability heuristics for user interface design*. Nielsen Norman Group.", url: "https://www.nngroup.com/articles/ten-usability-heuristics/" },
  { lessons: [6], apa: "Nielsen, J. (2012). *Usability 101: Introduction to usability*. Nielsen Norman Group.", url: "https://www.nngroup.com/articles/usability-101-introduction-to-usability/" },
  { lessons: [6], apa: "Norman, D. A. (2013). *The design of everyday things* (Rev. and expanded ed.). Basic Books." },
  { lessons: [6], apa: "Norman, D. A., & Draper, S. W. (Eds.). (1986). *User centered system design: New perspectives on human-computer interaction*. Lawrence Erlbaum Associates." },
  { lessons: [10], apa: "O'Boyle, E. H., Jr., Forsyth, D. R., Banks, G. C., & McDaniel, M. A. (2012). A meta-analysis of the Dark Triad and work behavior: A social exchange perspective. *Journal of Applied Psychology, 97*(3), 557–579.", url: "https://doi.org/10.1037/a0025679" },
  { lessons: [3], apa: "Paruthi, S., Brooks, L. J., D'Ambrosio, C., Hall, W. A., Kotagal, S., Lloyd, R. M., Malow, B. A., Maski, K., Nichols, C., Quan, S. F., Rosen, C. L., Troester, M. M., & Wise, M. S. (2016). Recommended amount of sleep for pediatric populations: A consensus statement of the American Academy of Sleep Medicine. *Journal of Clinical Sleep Medicine, 12*(6), 785–786.", url: "https://doi.org/10.5664/jcsm.5866" },
  { lessons: [10], apa: "Paulhus, D. L. (2014). Toward a taxonomy of dark personalities. *Current Directions in Psychological Science, 23*(6), 421–426.", url: "https://doi.org/10.1177/0963721414547737" },
  { lessons: [9], apa: "Paulhus, D. L., & Williams, K. M. (2002). The Dark Triad of personality: Narcissism, Machiavellianism, and psychopathy. *Journal of Research in Personality, 36*(6), 556–563.", url: "https://doi.org/10.1016/S0092-6566(02)00505-6" },
  { lessons: [9], apa: "Robinson, W. S. (1950). Ecological correlations and the behavior of individuals. *American Sociological Review, 15*(3), 351–357.", url: "https://doi.org/10.2307/2087176" },
  { lessons: [11], apa: "Sharma, M., Tong, M., Korbak, T., Duvenaud, D., Askell, A., Bowman, S. R., Cheng, N., Durmus, E., Hatfield-Dodds, Z., Johnston, S. R., Kravec, S., Maxwell, T., McCandlish, S., Ndousse, K., Rausch, O., Schiefer, N., Yan, D., Zhang, M., & Perez, E. (2023). *Towards understanding sycophancy in language models* [Preprint]. arXiv.", url: "https://doi.org/10.48550/arXiv.2310.13548" },
  { lessons: [6], apa: "Shneiderman, B. (1987). *Designing the user interface: Strategies for effective human-computer interaction*. Addison-Wesley." },
  { lessons: [8], apa: "Shneiderman, B. (2020). Human-centered artificial intelligence: Reliable, safe & trustworthy. *International Journal of Human–Computer Interaction, 36*(6), 495–504.", url: "https://doi.org/10.1080/10447318.2020.1741118" },
  { lessons: [8], apa: "Shneiderman, B. (2022). *Human-centered AI*. Oxford University Press." },
  { lessons: [10], apa: "Snook, B., Eastwood, J., Gendreau, P., Goggin, C., & Cullen, R. M. (2007). Taking stock of criminal profiling: A narrative review and meta-analysis. *Criminal Justice and Behavior, 34*(4), 437–453.", url: "https://doi.org/10.1177/0093854806296925" },
  { lessons: [8], apa: "Stanford Institute for Human-Centered Artificial Intelligence. (2026). *The 2026 AI Index report*. Stanford University.", url: "https://hai.stanford.edu/ai-index/2026-ai-index-report" },
  { lessons: [10], apa: "Stark, E. (2007). *Coercive control: How men entrap women in personal life*. Oxford University Press." },
  { lessons: [12], apa: "Sweet, P. L. (2019). The sociology of gaslighting. *American Sociological Review, 84*(5), 851–875.", url: "https://doi.org/10.1177/0003122419874843" },
  { lessons: [8], apa: "UNESCO. (2021). *Recommendation on the ethics of artificial intelligence*.", url: "https://www.unesco.org/en/artificial-intelligence/recommendation-ethics" },
  { lessons: [8], apa: "UNICEF. (2021). *Policy guidance on AI for children* (Version 2.0). UNICEF Office of Global Insight and Policy.", url: "https://www.unicef.org/innocenti/reports/policy-guidance-ai-children" },
  { lessons: [9], apa: "Vernon, P. A., Villani, V. C., Vickers, L. C., & Harris, J. A. (2008). A behavioral genetic investigation of the Dark Triad and the Big 5. *Personality and Individual Differences, 44*(2), 445–452.", url: "https://doi.org/10.1016/j.paid.2007.09.007" },
  { lessons: [6, 7], apa: "W3C. (2023). *Web content accessibility guidelines (WCAG) 2.2* [W3C Recommendation].", url: "https://www.w3.org/TR/WCAG22/" },
  { lessons: [1], apa: "Walters, W. H., & Wilder, E. I. (2023). Fabrication and errors in the bibliographic citations generated by ChatGPT. *Scientific Reports, 13*, Article 14045.", url: "https://doi.org/10.1038/s41598-023-41032-5" },
  { lessons: [6], apa: "Wertheimer, M. (1923). Untersuchungen zur Lehre von der Gestalt. II [Investigations in Gestalt theory, II]. *Psychologische Forschung, 4*, 301–350.", url: "https://doi.org/10.1007/BF00410640" },
  { lessons: [10], apa: "Whittle, H., Hamilton-Giachritsis, C., Beech, A., & Collings, G. (2013). A review of online grooming: Characteristics and concerns. *Aggression and Violent Behavior, 18*(1), 62–70.", url: "https://doi.org/10.1016/j.avb.2012.09.003" },
  { lessons: [10], apa: "Whitty, M. T. (2013). The scammers persuasive techniques model: Development of a stage model to explain the online dating romance scam. *British Journal of Criminology, 53*(4), 665–684.", url: "https://doi.org/10.1093/bjc/azt009" },
  { lessons: [10], apa: "Winters, G. M., & Jeglic, E. L. (2017). Stages of sexual grooming: Recognizing potentially predatory behaviors of child molesters. *Deviant Behavior, 38*(6), 724–733.", url: "https://doi.org/10.1080/01639625.2016.1197656" },
  { lessons: [7], apa: "Wood, W., & Rünger, D. (2016). Psychology of habit. *Annual Review of Psychology, 67*, 289–314.", url: "https://doi.org/10.1146/annurev-psych-122414-033417" },
  { lessons: [1], apa: "Xiong, M., Hu, Z., Lu, X., Li, Y., Fu, J., He, J., & Hooi, B. (2024). Can LLMs express their uncertainty? An empirical evaluation of confidence elicitation in LLMs. In *Proceedings of the Twelfth International Conference on Learning Representations (ICLR 2024)*.", url: "https://doi.org/10.48550/arXiv.2306.13063" }
];
